language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then
      pip install -r extra/requirements-py32.txt;
    fi
  - pip install .
  - pip install -r extra/requirements-test.txt
script:
  - nose2 -A '!no_travis' tests
