language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r extra/requirements-test.txt
  - pip install .
  - pip install coveralls
script:
  - pytest tests
after_success:
  - coveralls
branches:
  except:
    - /^play\/.*$/
