language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install -r extra/requirements-test.txt
  - pip install .
  - pip install coveralls
script:
  - pytest tests
after_success:
  - coveralls
branches:
  except:
    - /^play\/.*$/
